[package]
name = "url-short-fred"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
fred = "9.2.0"
tokio = { version = "1.40.0", features = ["full"] }
actix = "0.13.5"
actix-files = "0.6.6"
actix-web = "4.9.0"
serde_json = "1.0"
rand = "0.8.5"
